### ISSUE TITLE
Long installation on alpine docker

### ISSUE THREAD

**Issue by enzofrnt** [adamchainz/django-minify-html#201] opened 2024-06-20 15:19 UTC
### Not a minify-html bug

- [X] I am not reporting an issue with minification.

### Python Version

3.11.9

### Django Version

5.0.6

### Package Version

1.8.0

### Description

Hi, the installation of the package on an alpine container take between 200 and 300s, that may need some investigation ?

**Comment by adamchainz** [comment] 2024-06-20 16:01
Duplicate of #26.

**Closed by adamchainz** 2024-06-20 16:01 UTC
